# Generated by Django 3.1.2 on 2021-04-12 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='concatenation_points',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('con_type', models.CharField(max_length=20)),
                ('con_name', models.CharField(max_length=20)),
                ('con_points', models.FloatField()),
            ],
        ),
    ]
